=== keimpema/Mvp.Xml.NetStandard/library/Mvp.Xml.Tests/XPointer/northwind.dtd
<!ELEMENT CompanyName (#PCDATA)>
<!ELEMENT ContactName (#PCDATA)>
<!ELEMENT CustomerID (#PCDATA)>
<!ELEMENT CustomerIDs (CustomerID | CompanyName | ContactName | OrderIDs)+>
<!ELEMENT Item (OrderDate, ShipAddress)>
<!ATTLIST Item
    orderID ID #REQUIRED
>
<!ELEMENT OrderDate (#PCDATA)>
<!ELEMENT OrderIDs (Item+)>
<!ELEMENT ROOT (CustomerIDs)>
<!ELEMENT ShipAddress (#PCDATA)>

=== keimpema/Mvp.Xml.NetStandard/test/Mvp.Xml.Tests/XPointer/northwind.xml
<?xml version="1.0" encoding="utf-8" ?> 
<!DOCTYPE ROOT SYSTEM "northwind.dtd">
<ROOT>
    <CustomerIDs>
        <CustomerID> ALFKI</CustomerID>
        <CompanyName> Alfreds Futterkiste</CompanyName>
        <ContactName> Maria Anders</ContactName>
        <OrderIDs>
            <Item orderID="o10952">
                <OrderDate> 4/15/96</OrderDate>
                <ShipAddress> Obere Str. 57</ShipAddress>
            </Item>
            <Item orderID="o10643">
                <OrderDate> 9/25/95</OrderDate>
                <ShipAddress> Obere Str. 57</ShipAddress>
            </Item>
            <Item orderID="o10702">
                <OrderDate> 11/13/95</OrderDate>
                <ShipAddress> Obere Str. 57</ShipAddress>
            </Item>
            <Item orderID="o10692">
                <OrderDate> 11/3/95</OrderDate>
                <ShipAddress> Obere Str. 57</ShipAddress>
            </Item>
            <Item orderID="o10835">
                <OrderDate> 2/15/96</OrderDate>
                <ShipAddress> Obere Str. 57</ShipAddress>
            </Item>
            <Item orderID="o11011">
                <OrderDate> 5/9/96</OrderDate>
                <ShipAddress> Obere Str. 57</ShipAddress>
            </Item>
        </OrderIDs>
        <CustomerID> ANATR</CustomerID>
        <CompanyName> Ana Trujillo Emparedados y helados</CompanyName>
        <ContactName> Ana Trujillo</ContactName>
        <OrderIDs>
            <Item orderID="o10625">
                <OrderDate> 9/8/95</OrderDate>
                <ShipAddress> Avda. de la Constitución 2222</ShipAddress>
            </Item>
            <Item orderID="o10308">
                <OrderDate> 10/19/94</OrderDate>
                <ShipAddress> Avda. de la Constitución 2222</ShipAddress>
            </Item>
            <Item orderID="o10759">
                <OrderDate> 12/29/95</OrderDate>
                <ShipAddress> Avda. de la Constitución 2222</ShipAddress>
            </Item>
            <Item orderID="o10926">
                <OrderDate> 4/3/96</OrderDate>
                <ShipAddress> Avda. de la Constitución 2222</ShipAddress>
            </Item>
        </OrderIDs>
        <CustomerID> ANTON</CustomerID>
        <CompanyName> Antonio Moreno Taquería</CompanyName>
        <ContactName> Antonio Moreno</ContactName>
        <OrderIDs>
            <Item orderID="o10535">
                <OrderDate> 6/13/95</OrderDate>
                <ShipAddress> Mataderos  2312</ShipAddress>
            </Item>
            <Item orderID="o10677">
                <OrderDate> 10/23/95</OrderDate>
                <ShipAddress> Mataderos  2312</ShipAddress>
            </Item>
            <Item orderID="o10365">
                <OrderDate> 12/28/94</OrderDate>
                <ShipAddress> Mataderos  2312</ShipAddress>
            </Item>
            <Item orderID="o10856">
                <OrderDate> 2/28/96</OrderDate>
                <ShipAddress> Mataderos  2312</ShipAddress>
            </Item>
            <Item orderID="o10507">
                <OrderDate> 5/16/95</OrderDate>
                <ShipAddress> Mataderos  2312</ShipAddress>
            </Item>
            <Item orderID="o10573">
                <OrderDate> 7/20/95</OrderDate>
                <ShipAddress> Mataderos  2312</ShipAddress>
            </Item>
            <Item orderID="o10682">
                <OrderDate> 10/26/95</OrderDate>
                <ShipAddress> Mataderos  2312</ShipAddress>
            </Item>
        </OrderIDs>
        <CustomerID> AROUT</CustomerID>
        <CompanyName> Around the Horn</CompanyName>
        <ContactName> Thomas Hardy</ContactName>
        <OrderIDs>
            <Item orderID="o10864">
                <OrderDate> 3/4/96</OrderDate>
                <ShipAddress> Brook Farm Stratford St. Mary</ShipAddress>
            </Item>
            <Item orderID="o10793">
                <OrderDate> 1/24/96</OrderDate>
                <ShipAddress> Brook Farm
Stratford St. Mary</ShipAddress>
            </Item>
            <Item orderID="o10383">
                <OrderDate> 1/16/95</OrderDate>
                <ShipAddress> Brook Farm
Stratford St. Mary</ShipAddress>
            </Item>
            <Item orderID="o10558">
                <OrderDate> 7/5/95</OrderDate>
                <ShipAddress> Brook Farm
Stratford St. Mary</ShipAddress>
            </Item>
            <Item orderID="o10355">
                <OrderDate> 12/16/94</OrderDate>
                <ShipAddress> Brook Farm
Stratford St. Mary</ShipAddress>
            </Item>
            <Item orderID="o10743">
                <OrderDate> 12/18/95</OrderDate>
                <ShipAddress> Brook Farm
Stratford St. Mary</ShipAddress>
            </Item>
            <Item orderID="o10707">
                <OrderDate> 11/16/95</OrderDate>
                <ShipAddress> Brook Farm
Stratford St. Mary</ShipAddress>
            </Item>
            <Item orderID="o10920">
                <OrderDate> 4/2/96</OrderDate>
                <ShipAddress> Brook Farm
Stratford St. Mary</ShipAddress>
            </Item>
            <Item orderID="o10453">
                <OrderDate> 3/24/95</OrderDate>
                <ShipAddress> Brook Farm
Stratford St. Mary</ShipAddress>
            </Item>
            <Item orderID="o10741">
                <OrderDate> 12/15/95</OrderDate>
                <ShipAddress> Brook Farm
Stratford St. Mary</ShipAddress>
            </Item>
            <Item orderID="o11016">
                <OrderDate> 5/10/96</OrderDate>
                <ShipAddress> Brook Farm
Stratford St. Mary</ShipAddress>
            </Item>
            <Item orderID="o10953">
                <OrderDate> 4/15/96</OrderDate>
                <ShipAddress> Brook Farm
Stratford St. Mary</ShipAddress>
            </Item>
            <Item orderID="o10768">
                <OrderDate> 1/8/96</OrderDate>
                <ShipAddress> Brook Farm
Stratford St. Mary</ShipAddress>
            </Item>
        </OrderIDs>
        <CustomerID> BERGS</CustomerID>
        <CompanyName> Berglunds snabbköp</CompanyName>
        <ContactName> Christina Berglund</ContactName>
        <OrderIDs>
            <Item orderID="o10654">
                <OrderDate> 10/3/95</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
            <Item orderID="o10672">
                <OrderDate> 10/18/95</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
            <Item orderID="o10866">
                <OrderDate> 3/5/96</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
            <Item orderID="o10572">
                <OrderDate> 7/19/95</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
            <Item orderID="o10857">
                <OrderDate> 2/28/96</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
            <Item orderID="o10837">
                <OrderDate> 2/16/96</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
            <Item orderID="o10626">
                <OrderDate> 9/11/95</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
            <Item orderID="o10778">
                <OrderDate> 1/16/96</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
            <Item orderID="o10444">
                <OrderDate> 3/15/95</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
            <Item orderID="o10733">
                <OrderDate> 12/8/95</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
            <Item orderID="o10445">
                <OrderDate> 3/16/95</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
            <Item orderID="o10278">
                <OrderDate> 9/12/94</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
            <Item orderID="o10924">
                <OrderDate> 4/3/96</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
            <Item orderID="o10875">
                <OrderDate> 3/8/96</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
            <Item orderID="o10280">
                <OrderDate> 9/14/94</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
            <Item orderID="o10689">
                <OrderDate> 11/1/95</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
            <Item orderID="o10524">
                <OrderDate> 6/1/95</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
            <Item orderID="o10384">
                <OrderDate> 1/16/95</OrderDate>
                <ShipAddress> Berguvsvägen  8</ShipAddress>
            </Item>
        </OrderIDs>
        <CustomerID> BLAUS</CustomerID>
        <CompanyName> Blauer See Delikatessen</CompanyName>
        <ContactName> Hanna Moos</ContactName>
        <OrderIDs>
            <Item orderID="o10853">
                <OrderDate> 2/27/96</OrderDate>
                <ShipAddress> Forsterstr. 57</ShipAddress>
            </Item>
            <Item orderID="o10582">
                <OrderDate> 7/28/95</OrderDate>
                <ShipAddress> Forsterstr. 57</ShipAddress>
            </Item>
            <Item orderID="o10956">
                <OrderDate> 4/16/96</OrderDate>
                <ShipAddress> Forsterstr. 57</ShipAddress>
            </Item>
            <Item orderID="o10614">
                <OrderDate> 8/29/95</OrderDate>
                <ShipAddress> Forsterstr. 57</ShipAddress>
            </Item>
            <Item orderID="o10509">
